### ISSUE TITLE
USER STORY: Initial Django Set Up

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#1]
As a **Developer** I want to be able to **set up a new Django project** so that I can **create the project's structure**

## Acceptance Criteria

- The Django project is successfully initialized
- A new project named "decor_dreams" is created
- Add the first app to the project's settings

## Tasks

- [x] Task 1: Initialize a new Django project
- [x] Task 2: Create a new project with the name "decor_dreams"
- [x] Task 3: Create the first app and add it to settings.py
- [x] Task 4: Create an env.py file to hide secret keys
- [x] Task 5: Add env.py to .gitignore to keep secret keys private
- [x] Task 6: Create a new virtual environment to install packages

## Epic: #4

**Comment by IzabellaLopes** [comment]
![Image](https://github.com/IzabellaLopes/decor_dreams/assets/131386023/90b28c14-ca86-4835-9688-c118c935c7eb)

**Comment by IzabellaLopes** [comment]
Set up initial project/app and config files
