### ISSUE TITLE
USER STORY: Intuitive Site Navigation

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#12]
As a **Site User** I want to be able to **navigate intuitively around the site** so that I can **easily find the content I'm interested in**

## Acceptance Criteria

- User can easily locate navigation menu
- Navigation elements are logically organized and labeled

## Tasks

- [x] Task 1: Design intuitive navigation menu
- [x] Task 2: Ensure clear labeling of navigation links
- [x] Task 3: Test navigation flow across different devices

## Epic: #11
