### ISSUE TITLE
USER STORY: Browse Products

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#13]
As a **Site User** I want to be able to **see a comprehensive list of products available** so that I can **choose what to explore further**

## Acceptance Criteria

- Display All Products: Upon accessing the "Shop products" page, users see a list of all products fetched from the database
- Product Cards Layout: Each product is displayed as a card with a clear product image, title, and price
- Navigate to Product Details: Clicking on a product card redirects the user to the corresponding product's detailed page

## Tasks

- [x] Task 1: Create Product Model
- [x] Task 2: Create all_products view in views.py to list all products in database
- [x] Task 3: Create browse products HTML template
- [x] Task 4: Develop a user-friendly product card layout using bootstrap cards and make it responsive
- [x] Task 5: Link product cards to product detail page

## Epic: #11
