### ISSUE TITLE
USER STORY: Product Category

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#15]
As a **Shopper** I want to be able to **view a specific category of products** so that I can **find what I like more easily and have a smoother time shopping**

## Acceptance Criteria

Show Product Categories Dropdown: 
- After clicking the 'Shop Now' button, a menu should drop down showing various product categories
- Users should see a list of categories to choose from when they click

Display Products by Category:
- When a user selects a specific category from the dropdown menu, only products belonging to that category should be shown
- Users should see products relevant to the category they clicked on

## Tasks

- [x] Task 1: Create Category Model in products app and link to product model as a foreign key
- [x] Task 2:  Create the categories in the admin panel
- [x] Task 3:  Add category parameters to product urls in main_nav.html
- [x] Task 4: Write GET request logic in all_products view to filter products by category

## Epic: #11
