### ISSUE TITLE
USER STORY: Sort Products

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#17]
As a **Shopper** I want to be able to **arrange all products by price or title** so that I can **easily compare and view them**

## Acceptance Criteria

- A dropdown menu for sorting products should be visible on the right-hand side of the browse products page
- Clicking the dropdown arrow should reveal a list of predefined sorting options
- Upon selecting a sorting option, the products on the page should rearrange accordingly 

## Tasks

- [x] Task 1: Develop a sort selector on the products page and define sort parameters for select box options
- [x] Task 2: Modify the all_products view to handle GET requests for sorting products
- [x] Task 3: Write JavaScript code to update the product list when the sorting select box is changed
