### ISSUE TITLE
USER STORY: Browse Interior Design Consultation Services

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#19]
As a **Site User** I want to be able to **view a comprehensive list of interior design services provided** so that I can **understand the scope of each service and easily make an enquiry if I'm interested**

## Acceptance Criteria

- Upon clicking the "Design & Planning" tab in the navigation bar, the user should be directed to a page showcasing all available design services, complete with detailed descriptions and accompanying images
- The user should be able to click on an "Enquire Now" button adjacent to each Design Service, which will redirect them to an enquiry form

## Tasks

- [x] Task 1: Develop an Interior Design Service model to represent each service in the database
- [x] Task 2: Design an HTML template specifically for Interior Design Services
- [x] Task 3: Implement a view to list all Interior Design services stored in the Database
- [x] Task 4: Integrate the Interior Design Services option into the navigation menu for easy access
