### ISSUE TITLE
USER STORY: View Decor Dreams Projects

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#21]
As a **Site User** I want to be able to **browse through pictures of previous Decor Dreams interior design projects** so that I can **assess the quality of work and develop trust in the service provider**

## Acceptance Criteria

- Upon clicking the "Decor Dreams Projects" tab in the navigation bar, the user should be directed to a page showcasing images of past projects completed by Decor Dreams
- When viewed on desktop, hovering over an image should display the type of design service and location in the center of the image
- On mobile devices, the type of design service and location should be displayed below each image 

## Tasks

- [x] Task 1: Create a model for Decor Dreams Projects to organize data related to past interior design projects
- [x] Task 2: Develop an HTML template specifically tailored for showcasing Decor Dreams Projects
- [x] Task 3: Implement a view to list all previous interior design projects stored in the Database
- [x] Task 4: Integrate the Decor Dreams Projects option into the navigation menu for easy access
