### ISSUE TITLE
USER STORY: Sign Up

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#23]
As a **Site User** I want to be able to **sign up** so that I can **have a personal account on Decor Dreams**

## Acceptance Criteria

- A "signup" button should be visible in the user dropdown menu in the navigation bar
- Clicking the button should redirect me to the signup page
- Upon filling in my details and clicking submit, I should receive an email verification link
- Clicking the link and confirming should create a new account for me
- I should receive a success message confirming the creation of my new account

## Tasks

- [x] Task 1: Install allauth and add it to the installed apps
- [x] Task 2: Integrate allauth URLs into the project
- [x] Task 3: Implement email verification requirement
- [x] Task 4: Configure Gmail to send emails and add details to settings.py
- [x] Task 5: Add a signup link to the navigation bar
- [x] Task 6: Customize allauth signup form HTML templates
- [x] Task 7: Create a message to notify the user of successful signup

## Epic: #22
