### ISSUE TITLE
USER STORY: User Log in & Log out

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#24]
As a **Site User** I want to be able to **log in or log out of my account** so that I can **keep my account secure**

## Acceptance Criteria for Logged-Out User:

- The "Sign in" button should be visible on the navbar
- Clicking the button should redirect me to the log in page
- Upon filling in my details and clicking submit, I should be logged in
- I should receive a notification confirming successful log in
- If I enter incorrect credentials, I should receive feedback on the incorrectly entered information

## Acceptance Criteria for Logged-In User:

- Clicking the logout button should prompt me to confirm my intention to log out
- Upon confirmation, I should receive a notification confirming successful log out

## Tasks

- [x] Task 1: Install allauth and add it to installed apps
- [x] Task 2: Integrate allauth URLs into the project
- [x] Task 3: Add login and logout links to the navbar
- [x] Task 4: Customize allauth login and logout HTML templates
- [x] Task 5: Create success messages for successful login and logout
