### ISSUE TITLE
USER STORY: View Order History

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#26]
As a **Site User** I want to be able to **access my order history** so that I can **recall my past purchases**

## Acceptance Criteria

- When logged in, clicking on the user's profile should display a list of their previous orders
- Clicking on an order number should provide a detailed breakdown of the order by product

## Tasks

- [x] Task 1: Associate the user's profile with the order in the checkout success view
- [x] Task 2: Update the profile HTML template to include the order history
- [x] Task 3: Link the order number to the checkout success HTML page
