### ISSUE TITLE
USER STORY: Connect Database and S3 Storage and Stripe

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#3]
As a **Developer** I want to be able to **connect database, static/media storage and stripe payments** so that **data is accessible on deployment and payments are configured early**

## Acceptance Criteria

- Django's settings are configured to connect to the database
- Settings for ElephantSQL are appropriately configured
- Settings for static files and media directory roots are set up
- Database changes are migrated successfully

## Tasks

- [x] Task 1:  Configure Django's settings to connect to database
- [x] Task 2:  Configure settings for ElephantSQL
- [x] Task 3: Configure settings for static files and media directory roots
- [x] Task 4: Create superuser for admin panel
- [x] Task 5: Migrate DB changes
- [x] Task 6: Link AWS storage to settings.py and env.py
- [x] Task 7: Link Stripe authentication to env.py
- [x] Task 8: Store all config vars in heroku

**Comment by IzabellaLopes** [comment]
All required configuration for AWS, Stripe and ElephantSQL created
