### ISSUE TITLE
USER STORY: Add Products to Shopping Bag

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#30]
As a **Shopper** I want to be able to **add multiple products in varying quantities to my shopping bag** so that I can **purchase them all together when I'm ready**

## Acceptance Criteria

- On the product detail page, there should be a quantity selector and an "Add to Bag" button
- Clicking the "Add to Bag" button should add the selected quantity of the product to the user's shopping bag
- The user should be restricted from adding quantities outside the specified minimum and maximum thresholds

## Tasks

- [x] Task 1: Develop an "Add to Bag" form within the product_detail.html template
- [x] Task 2: Create an add_to_bag view and URL
- [x] Task 4: Include bag content in the context processor
- [x] Task 5: Implement JavaScript functionality to increase/decrease quantity in the bag
- [x] Task 6: Style the "Add to Bag" button and quantity selector
