### ISSUE TITLE
USER STORY: Total Shopping Bag

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#31]
As a **Shopper** I want to be able to **see a running total of my shopping bag as I add items** so that I can **keep track of the total cost**

## Acceptance Criteria

- When adding products to the bag, a message should display in the right-hand corner of the screen, showing the added item, a snapshot of bag contents, and the total cost

## Tasks

- [x] Task 1: Develop a toast HTML template for the success message
- [x] Task 2: Add the success message to the add to bag view
- [x] Task 3: Incorporate the shopping bag running total in the success HTML template
