### ISSUE TITLE
USER STORY: Modify Product Quantity

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#33]
As a **Shopper** I want to be able to **modify the quantity of individual products in my shopping bag** so that I can **easily make changes before finalizing my purchase**

## Acceptance Criteria

- While viewing the shopping bag, users should be able to modify the quantity of each product line item and observe the updated subtotal
- Users should also be able to delete products from the bag, with the bag updating accordingly

## Tasks

- [x] Task 1: Add quantity selector buttons and update/delete buttons to the shopping bag page
- [x] Task 2: Develop JavaScript functions to increase/decrease the quantity when the corresponding button is clicked
- [x] Task 3: Implement JavaScript to update the cart when the update button is clicked
- [x] Task 4: Develop JavaScript functionality to delete product line items when the delete button is clicked
- [x] Task 5: Create adjust_bag and delete_item views and URLs
