### ISSUE TITLE
USER STORY: Guest Checkout

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#36]
As a **Shopper** I want to be able to **checkout as a guest** so that I can **make a purchase without having to sign up for an account**

## Acceptance Criteria

- Clicking the secure checkout button in the shopping bag should display a checkout form and a summary of the order
- Users can fill in their details and have the option to save their personal information by creating an account
- Completing the form and submitting it should finalize the order

## Tasks

- [x] Task 1: Establish checkout models
- [x] Task 2: Develop a checkout form
- [x] Task 3: Create checkout views
- [x] Task 4: Install Django Crispy Forms for enhanced form rendering
- [x] Task 5: Design HTML templates for the checkout process
