### ISSUE TITLE
USER STORY: Email Confirmation

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#38]
As a **Shopper** I want to be able to **receive an email confirmation of my order** so that I can **have a record of my purchase**

## Acceptance Criteria

- Upon submitting their order, users should receive a confirmation email sent to the email address provided in their order form
- The confirmation email should include all the details of the order

## Tasks

- [x] Task 1: Develop email templates for order confirmation
- [x] Task 2: Update webhook handler to manage sending confirmation email
- [x] Task 3: Configure Gmail to send emails
