### ISSUE TITLE
USER STORY: Product Management

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#40]
As a **Store Owner** I want to be able to **add, edit, and delete products using a user-friendly interface** so that I can **ensure smooth management of the store's contents**

## Acceptance Criteria

- When logged in, the User drop-down menu should include a "Add a Product" option for the site owner
- Upon navigating to the Add a Product page, the site owner should encounter a user-friendly form for adding new products
- The product detail page should allow the site owner to edit and delete products
- Add/edit forms should include fields for all necessary information and feature form validation with clear feedback for any invalid inputs
- The site owner should receive a success message upon successfully adding, editing, or deleting a product

## Tasks

- [x] Task 1: Develop product form.py to handle product-related form functionality
- [x] Task 2: Create HTML pages for adding, editing, and confirming product deletion
- [x] Task 3:  views for adding, editing, and deleting products, incorporating form validation
- [x] Task 4: Implement error/success messages to provide feedback to the user
- [x] Task 5: Add edit and delete buttons to product cards and the product detail page
- [x] Task 6: Integrate the "Add Product" option into the User drop-down menu of the navigation bar
