### ISSUE TITLE
USER STORY: Decor Dreams Projects Management

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#42]
As a **Store Owner** I want to be able to **add, edit, and delete images and locations of previous Decor Dreams design projects** so that I can **effectively manage the site's content**

## Acceptance Criteria

- When logged in, the User drop-down menu should include a "Previous Project Management" option for the site owner
- Upon accessing the Previous Project Management page, the site owner should encounter a user-friendly form for adding details of a previous project to the site
- The form should feature fields for all required information and include form validation with clear feedback for any invalid inputs
- The site owner should be able to delete project images from the Previous Projects page by clicking the 'x' in the top right-hand corner of the picture
- Additionally, the site owner should have the ability to add project images from the Previous Projects page by clicking the 'Add Picture' button
- The site owner should receive a success message upon successfully adding, editing, or deleting an image.

## Tasks

- [x] Task 1: Develop Previous Projects form.py to manage previous project-related form functionality
- [x] Task 2: Create HTML pages for adding a Previous Project and confirming project deletion
- [x] Task 3: Write views for adding, editing, and deleting previous projects, including form validation
- [x] Task 4: Implement error/success messages to provide feedback to the user
- [x] Task 5: Create "Add Project", "Edit Project", and "Delete Project" buttons on the Previous Projects page
- [x] Task 6: Integrate the "Previous Project Management" option into the User drop-down menu of the navigation bar
