### ISSUE TITLE
USER STORY: Enquiries Dashboard

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#43]
As a **Store Owner** I want to be able to **view and delete customer enquiries directly on the front-end** so that I can **manage them without having to access the admin panel**

## Acceptance Criteria

- When logged in, the User drop-down menu should include an "Enquiries Management" option for the site owner
- Upon accessing the Enquiries Management page, the site owner should see a list of user enquiries sorted from newest to oldest
- Emails that have been read should be visually distinguished, such as being greyed out
- Clicking on an enquiry should redirect the site owner to the individual enquiry detail
- The site owner should be able to delete the enquiry or return to the list of enquiries
- The site owner should receive a success message upon successfully deleting an enquiry

## Tasks

- [x] Task 1: Create Enquiries Dashboard and Enquiry Detail HTML templates
- [x] Task 2: Develop Enquiries list view and detail view
- [x] Task 3: Apply CSS to style visited links, greying them out for visual distinction
- [x] Task 4: Integrate the "Enquiry Management" option into the User drop-down menu of the navigation bar
- [x] Task 5: Include success messages to provide feedback to the user upon deleting an enquiry
