### ISSUE TITLE
USER STORY: Design & Planning Consultation Enquiry

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#45]
As a **Site User** I want to be able to **submit an enquiry form** so that I can **contact the site owner**

## Acceptance Criteria

- Users can access the contact form by clicking the "Enquire Now" button on the Interior Design Services page or the 'Contact' button in the Nav bar
- The contact form should feature fields for all necessary information and include form validation with clear feedback for any invalid entries
- Users can select the type of enquiry from a drop-down menu to specify the nature of their message
- If logged in, the user's email address should be prepopulated in the form
- Upon submission of the form, users should receive an email confirmation of their enquiry for record-keeping purposes
- Users should also receive a success message confirming that their enquiry has been successfully submitted

## Tasks

- [x] Task 1: Create Contact model
- [x] Task 2: Develop Contact form.py
- [x] Task 3: Design HTML Template for the contact form
- [ ] Task 4: Implement a view to handle Get and Post requests for the contact form, including sending a confirmation email to the user
- [x] Task 5: Include error/success messages to provide feedback to the user
- [x] Task 6: Create "Enquire Now" button on the Design Services page and in the Nav Menu
