### ISSUE TITLE
USER STORY: Manage Testimonials

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#46]
As a **Site User** I want to be able to **add, edit, or delete a testimonial related to a consultation I received** so that I can **provide my feedback**

## Acceptance Criteria

- When a logged-in user clicks on the "Add Testimonial" button on the Testimonials page, they should see a user-friendly form where they can add a new testimonial to the site
- If the user is not logged in, they should be redirected to the login page
- The user should be able to edit and delete their own testimonials from the Testimonials Page
- The add/edit forms should include fields for all necessary information and feature form validation with clear feedback for any invalid entries
- Completed testimonials should automatically display the user's username and the date underneath the testimonial body
- Users should receive a success message upon successfully adding, editing, or deleting a testimonial

## Tasks

- [x] Task 1: Develop Add Testimonial form.py
- [x] Task 2: Create HTML pages for adding, editing, and confirming deletion of testimonials
- [x] Task 3: Write views for adding, editing, and deleting testimonials, including form validation
- [x] Task 4: Implement error/success messages to provide feedback to the user
- [x] Task 5: Add edit and delete buttons to the testimonial page
- [x] Task 6: Create an "Add Testimonial" button on the Testimonials page
