### ISSUE TITLE
USER STORY: Facebook marketing promotional page

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#50]
As a **Developer** I want to be able to **create a Facebook marketing promotional page to spotlight the Decor Dreams** so that I can **attract potential customers to the website**

## Acceptance Criteria

- The Facebook page should accurately represent our brand and showcase what we offer
- Content on the page should be interesting, informative, and help us achieve our marketing goals
- Include good-quality pictures, catchy writing, and useful links to guide people to our website or other online spots
- Update the Facebook page regularly with new stuff to keep people interested and gain more followers

## Tasks

- [x] Task 1: Figure out what our brand looks like on Facebook, including the logo, colors, and pictures
- [x] Task 2: Set up a Facebook Business account or use one we already have to make the page
- [x] Task 3: Make the page look like Decor Dreams by changing the layout, cover photo, profile picture, and other parts to match my brand
- [x] Task 4: Write cool and helpful stuff for the page, like what we're about, descriptions of our stuff, and messages to get people interested
- [x] Task 5: Put up great pictures of what we sell or do on the page
- [x] Task 6: Add links to our website, online store, contact info, and other social media pages.
- [x] Task 7: Turn on cool features like reviews, messages, and buttons that tell people what to do next

**Comment by IzabellaLopes** [comment]
![facebook](https://github.com/IzabellaLopes/decor_dreams/assets/131386023/1105041a-ee72-4e0e-9a5b-b0d1b0b10489)
