### ISSUE TITLE
USER STORY: Site Navigation

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/decor_dreams#9]
As a **Developer** I can **enhance Decor Dreams's site navigation** so that **I provide an intuitive and user-friendly journey within the e-commerce website**

## Acceptance Criteria

- The navigation menu is clear, allowing users to easily locate key sections of the website
- Users can seamlessly navigate between pages, fostering a smooth exploration of the home products and interior design service

## Tasks

- [x] Task 1: Implement a clear and organized navigation menu
- [x] Task 2: Ensure straightforward links to essential sections, such as home, shop products, design & planning, decor dreams projects, testimonials and contact us.
- [x] Task 3: Enhance the mobile navigation menu for a smooth experience on smaller screens
- [x] Task 4: Conduct usability testing to validate the effectiveness of the improved navigation
- [x] Task 5: Gather user feedback to further refine and optimize the site navigation for Decor Dreams

## Epic: #5
